ARG BUILD_FROM=alpine:3.14.0
FROM ${BUILD_FROM}

# Environment variables
ENV \
    HOME="/root" \
    LANG="C.UTF-8" \
    PS1="$(whoami)@$(hostname):$(pwd)$ " \
    S6_BEHAVIOUR_IF_STAGE2_FAILS=2 \
    S6_CMD_WAIT_FOR_SERVICES=1 \
    TERM="xterm-256color"

# Set shell
SHELL ["/bin/ash", "-o", "pipefail", "-c"]

# Install base system
ARG BUILD_ARCH=amd64
RUN \
    set -o pipefail \
    \
    && apk add --no-cache \
        bash=5.1.4-r0 \
        curl=7.78.0-r0 \
        jq=1.6-r1 \
        tzdata=2021a-r0 \
    \
    && S6_ARCH="${BUILD_ARCH}" \
    && if [ "${BUILD_ARCH}" = "i386" ]; then S6_ARCH="x86"; fi \
    && if [ "${BUILD_ARCH}" = "armv7" ]; then S6_ARCH="arm"; fi \
    \
    && curl -L -s "https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-${S6_ARCH}.tar.gz" \
        | tar zxvf - -C / \
    \
    && mkdir -p /etc/fix-attrs.d \
    && mkdir -p /etc/services.d \
    \
    && curl -J -L -o /tmp/bashio.tar.gz \
        "https://github.com/hassio-addons/bashio/archive/v0.13.1.tar.gz" \
    && mkdir /tmp/bashio \
    && tar zxvf \
        /tmp/bashio.tar.gz \
        --strip 1 -C /tmp/bashio \
    \
    && mv /tmp/bashio/lib /usr/lib/bashio \
    && ln -s /usr/lib/bashio/bashio /usr/bin/bashio \
    \
    && curl -L -s -o /usr/bin/tempio \
        "https://github.com/home-assistant/tempio/releases/download/2021.05.0/tempio_${BUILD_ARCH}" \
    && chmod a+x /usr/bin/tempio \
    \
    && rm -f -r \
        /tmp/*

# Entrypoint & CMD
ENTRYPOINT ["/init"]

LABEL maintainer="Ludger Berse <lb@sell-e.de>"
LABEL name="salt4unraid"
LABEL githu.repo="https://github.com/lubeda/salt4gui"

ENV SALT_VERSION="3003-r1"
ENV SALT_APIPASSWORD="salt"

# SALT specific

RUN \
    apk update \
    \
    && apk add --no-cache\
    linux-pam=1.5.1-r1\
    py3-libvirt\
    py3-pip \
    qemu-img \
    salt-master=${SALT_VERSION} \
    salt-minion=${SALT_VERSION} \
    salt-api=${SALT_VERSION} \
    salt-ssh=${SALT_VERSION} \
    salt-cloud=${SALT_VERSION}
    
RUN pip install cherrypy docker

# Copy root filesystem
COPY rootfs /

# some volume configuration for the saltmaster
VOLUME ["/pki", "/var/cache/salt", "/var/log/salt","/etc/salt"]
EXPOSE 3333 4505 4506
